version: '3'

services: 
  mysql_challange:
    image: mysql_challange
    networks:
      - custom_network_compose
  rest_challange:
    image: rest_challange
    depends_on:
      - mysql_challange
    ports:
      - 8020:8080
    networks:
      - custom_network_compose
  frontend_challange:
    image: frontend_challange
    depends_on:
      - rest_challange
    ports:
      - 8010:8080
    networks:
      - custom_network_compose
networks:
        custom_network_compose:
